const LOTUS_AUTH_TOKEN='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.Nyc9DtmpVVHvEKWVkwvio13QHsSvoUr2_sStjk31BGE'
const LOTUS_URL='ws://localhost:4502/rpc/v0'
